### ISSUE TITLE
Status code error

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt_authoring#136]
getting regular errors in express:

RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:192:11)
    at ServerResponse.writeHead (/var/www/deltanet.adaptbuilder.com/node_modules/compression/node_modules/on-headers/index.js:55:19)
    at ServerResponse.writeHead (/var/www/deltanet.adaptbuilder.com/node_modules/express-session/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.end (/var/www/deltanet.adaptbuilder.com/node_modules/compression/index.js:102:14)

Could be due to this line not excluding invalid status codes:
https://github.com/adaptlearning/adapt_authoring/blob/bbee5b95e34a69c47ec9c6613ce2d21882927599/lib/application.js#L243

e.g:
res.statusCode = err.statusCode >= 100 && err.statusCode < 600 ? err.statusCode : 500;

Definitely happens sometimes when zips are downloaded.

**Comment by dancgray** [comment]
https://expressjs.com/en/guide/error-handling.html

**Comment by dancgray** [comment]
Duplicate of https://github.com/deltanet/adapt_authoring/pull/238
