### ISSUE TITLE
import issues - cannot import from framework or AT

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt_authoring#191]
ReferenceError: configuration is not defined
    at AdaptOutput.ImportSource (/source/deltanet/github/adapt_authoring/plugins/output/adapt/importsource.js:51:38)

**Comment by dancgray** [comment]
ReferenceError: configuration is not defined
    at AdaptOutput.Import (/source/deltanet/github/adapt_authoring/plugins/output/adapt/import.js:21:38)

**Comment by dancgray** [comment]
Fixed in productionLive
