### ISSUE TITLE
No tenant/shared courses are returned from api/content/course in Multi tenancy test

### ISSUE THREAD

**Issue by dancgray** [deltanet/adapt_authoring#251]
Sometimes all courses seem to "disappear", i.e. nothing is returned from api/content/course. After restarting the server the courses are then returned from that query.

The following error is logged.

```1|test.ada | Error: Can't set headers after they are sent.
1|test.ada |     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
1|test.ada |     at ServerResponse.header (/var/www/test.adaptbuilder.co.uk/node_modules/express/lib/response.js:767:10)
1|test.ada |     at ServerResponse.send (/var/www/test.adaptbuilder.co.uk/node_modules/express/lib/response.js:170:12)
1|test.ada |     at ServerResponse.json (/var/www/test.adaptbuilder.co.uk/node_modules/express/lib/response.js:267:15)
1|test.ada |     at /var/www/test.adaptbuilder.co.uk/lib/tenantmanager.js:96:26
1|test.ada |     at /var/www/test.adaptbuilder.co.uk/lib/tenantmanager.js:368:24
1|test.ada |     at /var/www/test.adaptbuilder.co.uk/lib/tenantmanager.js:264:11
1|test.ada |     at /var/www/test.adaptbuilder.co.uk/node_modules/async/dist/async.js:1074:9
1|test.ada |     at /var/www/test.adaptbuilder.co.uk/node_modules/async/dist/async.js:421:16
1|test.ada |     at replenish (/var/www/test.adaptbuilder.co.uk/node_modules/async/dist/async.js:941:25)
1|test.ada |     at iterateeCallback (/var/www/test.adaptbuilder.co.uk/node_modules/async/dist/async.js:931:17)
1|test.ada |     at /var/www/test.adaptbuilder.co.uk/node_modules/async/dist/async.js:906:16
1|test.ada |     at /var/www/test.adaptbuilder.co.uk/node_modules/async/dist/async.js:1071:13
1|test.ada |     at /var/www/test.adaptbuilder.co.uk/node_modules/async/dist/async.js:1074:9
1|test.ada |     at /var/www/test.adaptbuilder.co.uk/node_modules/async/dist/async.js:421:16
1|test.ada |     at replenish (/var/www/test.adaptbuilder.co.uk/node_modules/async/dist/async.js:941:25)
1|test.ada |     at iterateeCallback (/var/www/test.adaptbuilder.co.uk/node_modules/async/dist/async.js:931:17)
1|test.ada |     at /var/www/test.adaptbuilder.co.uk/node_modules/async/dist/async.js:906:16
1|test.ada |     at /var/www/test.adaptbuilder.co.uk/node_modules/async/dist/async.js:1071:13
1|test.ada |     at /var/www/test.adaptbuilder.co.uk/lib/installHelpers.js:429:7
1|test.ada |     at /var/www/test.adaptbuilder.co.uk/node_modules/async/dist/async.js:421:16
1|test.ada |     at replenish (/var/www/test.adaptbuilder.co.uk/node_modules/async/dist/async.js:941:25)
```

The following routes are called before this error:
get /
post /api/login
post /api/user
get /api/tenant
get /api/extensiontype
get /api/componenttype
get /api/role
get /api/autocomplete/tag
get /api/content/schema
get /api/tenant/:id
get /api/shared/course
post /api/tenant
get /api/authcheck
get /lang/:lang
get /config/config.json

Restarting the application resolves the problem.

Steps to reproduce.
1- Create a new adapt tenant for an existing tenant in astute
2- Courses assigned to super user in master tenant are no longer returned from running API GET api/content/course. So no courses are displayed in dashboard.

**Comment by dancgray** [comment]
Seems to be caused when you create a new tenant in Astute.

**Comment by dancgray** [comment]
Fixed in https://github.com/deltanet/adapt_authoring/pull/255
